### ISSUE TITLE
Extraneous characters expected in Path

### ISSUE THREAD

**Issue by roberte3** [jtrivedi/CoreSync#4]
When I compare the output and expected inputs for CoreSync, the CoreSync system is including extraneous characters in the path, compared to other tools. 

2015-08-25 08:25:34.363 coreSyncTest[27830:1154852] CoreSync Changes: [
  {
    "op" : "replace",
    "path" : "\/Appetizers\/[1]\/title",
    "value" : "Crispy Cheese Ravioli"
  }
]
2015-08-25 08:25:34.363 coreSyncTest[27830:1154852] &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
2015-08-25 08:25:34.364 coreSyncTest[27830:1154852] JSONTools Changes (https://github.com/grgcombs/JSONTools):
 [
  {
    "op" : "replace",
    "path" : "\/Appetizers\/1\/title",
    "value" : "Extra Crispy Cheese Ravioli"
  }
]
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
2015-08-25 08:25:34.366 coreSyncTest[27830:1154852] Java Backend Changes: (Unknown jSONPatch library)
[
    {"op":"replace",
     "path":"/Appetizers/1/description",
     "value":"Pasta sauce "}
]

**Comment by jtrivedi** [comment]
Ah yes, this is because CoreSync encodes array indexes in paths slightly differently than the JSONPatch spec does. 

Instead of encoding the path as `Appetizers/1/title`, it wraps the index in brackets (i.e., `Appetizers/[1]/title`).

This partially by design, because an integer value can also be a key (i.e., "1"), so the brackets differentiate a string key from an array index.

However, I'm open to changing this for two reasons. Technically `"[1]"` can also be a key, and more importantly, it is a departure from JSONPatch. Let me look into this a bit.

**Comment by jtrivedi** [comment]
@roberte3: Fixed, thanks!
